const { Client } = require("pg");
const { DB } = require("./config");

(async () => {
  const usersTable = `
        CREATE TABLE IF NOT EXISTS users(
            id      INT     PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY NOT NULL,
            email   VARCHAR(50),
            password    TEXT,
            firstName   VARCHAR(50),
            lastName    VARCHAR(50),
            createdAt     DATE,
            modifiedAt  DATE
        );
        `;
  const productsTable = `
        CREATE TABLE IF NOT EXISTS products(
            id INT  PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY NOT NULL,
            name VARCHAR(50) NOT NULL,
            price INT NOT NULL,
            description VARCHAR(50) NOT NULL,
            image_url VARCHAR(50) NOT NULL,
            createdAt     DATE NOT NULL,
            modifiedAt  DATE NOT NULL
        );
    `;
  const ordersTable = `
        CREATE TABLE IF NOT EXISTS orders (
            id INT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY NOT NULL,
            userId INT NOT NULL,
            total INT NOT NULL,
            status VARCHAR(50) NOT NULL,
            createdAt  DATE NOT NULL,
            modifiedAt  DATE NOT NULL,
            FOREIGN KEY (userId) REFERENCES users(id)
        );
    `;
  const orderItemsTable = `
        CREATE TABLE IF NOT EXISTS orderItems (
            id INT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY NOT NULL,
            quantity INT NOT NULL,
            price INT NOT NULL,
            productId INT NOT NULL,
			orderId INT NOT NULL,
            createdAt  DATE NOT NULL,
            modifiedAt  DATE NOT NULL,
            FOREIGN KEY (orderId) REFERENCES orders(id),
            FOREIGN KEY (productId) REFERENCES products(id)
        );
    `;
  const cartsTable = `
        CREATE TABLE IF NOT EXISTS carts (
            id INT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY NOT NULL,
            userId INT NOT NULL,
            createdAt  DATE NOT NULL,
            modifiedAt  DATE NOT NULL,
            FOREIGN KEY (userId) REFERENCES users(id)
        );
    `;
  const cartItemsTable = `
        CREATE TABLE IF NOT EXISTS cartItems (
            id INT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY NOT NULL,
            quantity INT NOT NULL,
            cartId INT NOT NULL,
            productId INT NOT NULL,
            createdAt  DATE NOT NULL,
            modifiedAt  DATE NOT NULL,
            FOREIGN KEY (cartId) REFERENCES carts(id),
            FOREIGN KEY (productId) REFERENCES products(id)
        );
    `;
  try {
    const db = new Client({
      user: DB.PGUSER,
      host: DB.PGHOST,
      database: DB.PGDATABASE,
      password: DB.PGPASSWORD,
      port: DB.PGPORT,
    });
    await db.connect();

    await db.query(usersTable);
    await db.query(productsTable);
    await db.query(ordersTable);
    await db.query(orderItemsTable);
    await db.query(cartsTable);
    await db.query(cartItemsTable);

    await db.end();
  } catch (error) {
    console.log("DATABSE CERATION ERROR:", error);
  }
})();
